### ISSUE TITLE
Handle literal cons?

### ISSUE THREAD

**Issue by porglezomp** [cgaebel/sexp#3]
It would be nice to be able to represent any standard s-expression, which means being able to represent things like `(a . b)` and `(1 2 3 4 . 5)`. I'm not sure the best way to go about this though. Completely breaking backward compatibility, you could parse `(1 2 3 4)` into `List(vec![I(1), I(2), I(3), I(4), Nil])`. A probably  much better way would be to add another variant to `Sexp`, perhaps `Cons(Vec<Sexp>)` that would represent a list that ends with something besides `nil`.

**Comment by cgaebel** [comment]
Is there any gain in expressivity from literal cons?

**Comment by porglezomp** [comment]
To be fair, this is why I asked #6. If you're mostly interested in serialization, then this really shouldn't be an issue and can probably be safely closed.
